### PR TITLE
fix the broken parsing

### PR DESCRIPTION
**Pull request by piotrostr**
this might require some more work but I got it makes the deserialization of the given liquidity pool data yield the right values

### CODE REVIEW

**Comment by RainRaydium** [comment]
> this might require some more work but I got it makes the deserialization of the given liquidity pool data yield the right values

There is no need to update.Please use the new version layout..

**Comment by piotrostr** [comment]
@RainRaydium you mean the Raydium V3 that is in beta? https://beta.raydium.io/

I was targeting the current Raydium LP program (`675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8`)

**Comment by piotrostr** [comment]
this could be documented somewhere since the examples provided in the https://github.com/raydium-io/raydium-library client are not working out-of-the-box

**Comment by grebenyuksv** [comment]
> new version layout

what do you mean, @RainRaydium? [`LIQUIDITY_STATE_LAYOUT_V5`](https://github.com/raydium-io/raydium-sdk/blob/f4b7f47e744c12a8b0119b85e16d0d8274aa5ba9/src/liquidity/layout.ts#L68)? https://github.com/raydium-io/raydium-library/blob/master/client/src/main.rs#L204-L205 

I don't believe the example from https://github.com/raydium-io/raydium-library/blob/master/client/src/main.rs#L204-L205 just doesn't work. What am I doing wrong? 🤔 

The alignment of `swap_pc_in_amount` doesn't seem to match the on-chain data from that pool id:

image

Rust assumes the offset of `swap_pc_in_amount` inside `StateData` is 0x70, but it seems to be 0x68 on chain. I've tried different Rust versions from 1.73 to 1.79 on an M2 MacBook and in the official `rust:1.x.0-slim` Docker containers. 

The TS example from https://github.com/raydium-io/raydium-sdk-V2-demo/blob/master/src/amm/swap.ts works.

**Comment by grebenyuksv** [comment]
Did you understand that answer, @piotrostr ? Is there a pool where the example from raydium-library works out of the box? 🤔

**Pull request closed without merging**
